export enum ErrorCode {
  // Auth — AUTH_XXX
  AUTH_INVALID_CREDENTIALS = 'AUTH_001',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_002',
  AUTH_TOKEN_EXPIRED = 'AUTH_003',
  AUTH_TOKEN_INVALID = 'AUTH_004',
  AUTH_NO_REFRESH_TOKEN = 'AUTH_005',

  // Applications — APP_XXX
  APP_NOT_FOUND = 'APP_001',
  APP_FORBIDDEN = 'APP_002',
}